skillset = {
    "Divine Blessing",
    "Aim Booster",
    "Minds Eye",
    "Guard Up",
    "Earplugs",
    "Constitution",
    "Affinity Sliding",
    "Recovery Up",
    "Fire Attack",
    "Fire Resistance",
    "Ice Resistance",
    "Dragon Resistance",
    "Paralysis Resistance",
    "Muck Resistance",
    "Botanist",
    "Bombardier",
    "Carving Pro",
    "Leap Of Faith",
    "Wall Runner",
    "Stamina Thief",
    "Critical Element",
    "Horn Maestro",
    "Recovery Speed",
    "Water Resistance",
    "Thunder Resistance",
    "Poison Resistance",
    "Sleep Resistance",
    "Blast Resistance",
    "Blast Attack",
    "Geologist",
    "Item Prolonger",
    "Power Prolonger",
    "Fortify",
    "Hunger Resistance",
    "Diversion",
    "Wirebug Whisperer",
    "Resuscitate",
    "Critical Eye",
    "Maximum Might",
    "Heroics",
    "Special Ammo Boost",
    "Defense Boost",
    "Flinch Free",
    "Load Shells",
    "Stamina Surge",
    "Guard",
    "Steadiness",
    "Attack Boost",
    "Handicraft",
    "Quick Sheathe",
    "Free Meal",
    "Stun Resistance",
    "Ammo Up",
    "Offensive Guard",
    "Mushroomancer",
    "Water Attack",
    "Rapid Morph",
    "Ice Attack",
    "Protective Polish",
    "Speed Sharpening",
    "Partbreaker",
    "Bludgeoner",
    "Tremor Resistance",
    "Marathon Runner",
    "Artillery",
    "Focus",
    "Poison Attack",
    "Recoil Down",
    "Reload Speed",
    "Paralysis Attack",
    "Evade Window",
    "Dragon Attack",
    "Bubbly Dance",
    "WideRange",
    "Blight Resistance",
    "Speed Eating",
    "Slugger",
    "Punishing Draw",
    "Evade Extender",
    "Counterstrike",
    "Windproof",
    "Agitator",
    "Peak Performance",
    "Resentment",
    "Critical Boost",
    "Weakness Exploit",
    "Latent Power",
    "Sleep Attack",
    "Razor Sharp",
    "Spare Shot",
    "Pierce Up",
    "Spread Up",
    "Capture Master",
    "Good Luck",
    "Jump Master",
    "Hellfire Cloak",
    "Normal/Rapid Up",
    "Master's Touch",
    ""
}

skills = [
    "Divine Blessing",
    "Aim Booster",
    "Minds Eye",
    "Guard Up",
    "Earplugs",
    "Constitution",
    "Affinity Sliding",
    "Recovery Up",
    "Fire Attack",
    "Fire Resistance",
    "Ice Resistance",
    "Dragon Resistance",
    "Paralysis Resistance",
    "Muck Resistance",
    "Botanist",
    "Bombardier",
    "Carving Pro",
    "Leap Of Faith",
    "Wall Runner",
    "Stamina Thief",
    "Critical Element",
    "Horn Maestro",
    "Recovery Speed",
    "Water Resistance",
    "Thunder Resistance",
    "Poison Resistance",
    "Sleep Resistance",
    "Blast Resistance",
    "Blast Attack",
    "Geologist",
    "Item Prolonger",
    "Power Prolonger",
    "Fortify",
    "Hunger Resistance",
    "Diversion",
    "Wirebug Whisperer",
    "Resuscitate",
    "Critical Eye",
    "Maximum Might",
    "Heroics",
    "Special Ammo Boost",
    "Defense Boost",
    "Flinch Free",
    "Load Shells",
    "Stamina Surge",
    "Guard",
    "Steadiness",
    "Attack Boost",
    "Handicraft",
    "Quick Sheathe",
    "Free Meal",
    "Stun Resistance",
    "Ammo Up",
    "Offensive Guard",
    "Mushroomancer",
    "Water Attack",
    "Rapid Morph",
    "Ice Attack",
    "Protective Polish",
    "Speed Sharpening",
    "Partbreaker",
    "Bludgeoner",
    "Tremor Resistance",
    "Marathon Runner",
    "Artillery",
    "Focus",
    "Poison Attack",
    "Recoil Down",
    "Reload Speed",
    "Paralysis Attack",
    "Evade Window",
    "Dragon Attack",
    "Bubbly Dance",
    "WideRange",
    "Blight Resistance",
    "Speed Eating",
    "Slugger",
    "Punishing Draw",
    "Evade Extender",
    "Counterstrike",
    "Windproof",
    "Agitator",
    "Peak Performance",
    "Resentment",
    "Critical Boost",
    "Weakness Exploit",
    "Latent Power",
    "Sleep Attack",
    "Razor Sharp",
    "Spare Shot",
    "Pierce Up",
    "Spread Up",
    "Capture Master",
    "Good Luck",
    "Jump Master",
    "Hellfire Cloak",
    "Normal/Rapid Up",
    "Master's Touch",
]
rarity = ['3','4','5','6','7']
slots = ['0','1','2','3','1-1','1-1-1','2-1','2-1-1','2-2','2-2-1','3-1','3-2','3-2-1','3-1-1']
skilllevel = ['1','2','3','4','5']
